### ISSUE TITLE
Call to a member function add_settings() on boolean

### ISSUE THREAD

**Issue by w33zy** [afragen/github-updater#566]
I get the error below on activating the newest version of the plugin. 

```
2017/07/04 16:37:16 [error] 25889#25889: *1360424 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function add_settings() on boolean in /var/www/website.com/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Settings.php:414

Stack trace:

#0 /var/www/website.com/htdocs/wp-includes/class-wp-hook.php(298): Fragen\GitHub_Updater\Settings->page_init('')
#1 /var/www/website.com/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/website.com/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/website.com/htdocs/wp-admin/admin.php(154): do_action('admin_init')
#4 /var/www/website.com/htdocs/wp-admin/index.php(10): require_once('/var/www/website...')
#5 {main}
```

**Comment by afragen** [comment]
Can you describe the steps to reproduce?

**Comment by afragen** [comment]
I think https://github.com/afragen/github-updater/commit/4a3037e504c7d3d9f4f183340bfeef11d0052cd0 should fix it.

I never saw that in testing. Thanks.

**Comment by w33zy** [comment]
Sorry for being so terse in my description. 
All I did was clone the repo and reloaded my WP and I got a 500 HTTP error. I then checked my server logs to find those errors.

I'll check you fix now.

**Comment by w33zy** [comment]
It is working now
