### ISSUE TITLE
Error when using Gitea

### ISSUE THREAD

**Issue by steffenster** [afragen/github-updater#686]
I use github-update for my selfhosted Gitea Installation. In you latest udpate There is an error:

```
2018/05/16 12:47:33 [error] 10250#10250: *1191 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Access to undeclared static property: Fragen\GitHub_Updater\Base::$auth_required in /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/API/Gitea_API.php:601
Stack trace:
#0 /srv/testwp.de/htdocs/wp-includes/class-wp-hook.php(286): Fragen\GitHub_Updater\API\Gitea_API->gitea_error('')
#1 /srv/testwp.de/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array)
#2 /srv/testwp.de/htdocs/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /srv/testwp.de/htdocs/wp-admin/admin-header.php(267): do_action('admin_notices')
#4 /srv/testwp.de/htdocs/wp-admin/admin.php(230): require_once('/srv/testwp.de/...')
#5 /srv/testwp.de/htdocs/wp-admin/options-general.php(10): require_once('/srv/testwp.de/...')
#6 {main}
  thrown in /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/API/Gitea_API.php on line 601" while reading upstream, client: 127.0.0.1, server: testwp.de.local, request: "GET /wp-admin/options-general.php?page=github-updater HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "testwp.de.local", referrer: "http://testwp.de.local/wp-admin/options-general.php?page=github-updater&tab=github_updater_settings&subtab=github"
```

I hotfixed this for me by removing this: https://github.com/afragen/github-updater/blob/7be3d8533c21eb5efdfbe4f976305ef1b8ca5208/src/GitHub_Updater/API/Gitea_API.php#L601

**Comment by afragen** [comment]
Sorry, I see you are using the `develop` branch. Thanks for the bug report. I’ll get this fixed and report back.

**Comment by afragen** [comment]
This should now be fixed. https://github.com/afragen/github-updater/commit/43708b83677e974060ec57fbab354087aa054d91
