### ISSUE TITLE
Fatal Error - readme.txt

### ISSUE THREAD

**Issue by steffenster** [afragen/github-updater#690]
I can't really put this together. If I delete the readme.txt there is no error.

```
Warning: Illegal string offset 'sections' in /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 646

Fatal error: Uncaught Error: Cannot use string offset as an array in /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/API.php:646 
Stack trace: 
#0 /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/API/Gitea_API.php(236): Fragen\GitHub_Updater\API->set_readme_info('# Onlinerechner...') 
#1 /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(495): Fragen\GitHub_Updater\API\Gitea_API->get_remote_readme() 
#2 /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Plugin.php(205): Fragen\GitHub_Updater\Base->get_remote_repo_meta(Object(stdClass)) 
#3 /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(242): Fragen\GitHub_Updater\Plugin->get_remote_plugin_meta() 
#4 /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Base.php(209): Fragen\GitHub_Updater\Base->get_meta_plugins() 
#5 /srv/testwp.de/htdocs/wp-includes/class-wp-hook.php(286): Fragen\GitHub_Updater\Base->load('') 
#6 in /srv/testwp.de/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/API.php on line 646
```

**Comment by afragen** [comment]
There is likely an invalid readme.txt file in a plugin. Properly formatting it should fix the issue.

Can you share a link to the readme.txt file?

**Comment by steffenster** [comment]
My readme.txt file is pretty simple

```
# Onlinerechner

Requires PHP: 5.6
Tested up to: 4.9.6
Stable tag: master

## Description

This plugin provides multiple shortcodes for different calculators.
```

**Comment by afragen** [comment]
I think the issue is by naming the file `readme.txt` WP assumes a certain structure. My recommendation is one of the following.

1. Rename the file to `README.md`
2. Make sure `readme.txt` is valid, https://wordpress.org/plugins/developers/readme-validator/
