### ISSUE TITLE
Upgrading brings WordPress down (500)

### ISSUE THREAD

**Issue by vilmosioo** [afragen/github-updater#768]
Upgrading from 8.4.1 to 8.6.3 on a Bitnami powered WP site, gives the following error:

PHP Fatal error:  Uncaught Error: Class 'Fragen\\Singleton' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/GHU_Trait.php:50
Stack trace:
0 wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Init.php(33): Fragen\\GitHub_Updater\\Init->load_options()
1 wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(57): Fragen\\GitHub_Updater\\Init->__construct()
2 wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(20): Fragen\\GitHub_Updater\\Bootstrap->run('/opt/bitnami/ap...', '/opt/bitnami/ap...')
3 wordpress/htdocs/wp-content/plugins/github-updater/github-updater.php(53): require_once('/opt/bitnami/ap...')
4 wordpress/htdocs/wp-settings.php(305): include_once('/opt/bitnami/ap...')
5 wordpress/htdocs/wp-config.php(108): require_once('/opt/bitnami/ap...')

**Comment by afragen** [comment]
Can you look in the GHU `vendor/afragen` does it match what’s on GitHub?

**Comment by vilmosioo** [comment]
I'm guessing it doesn't. I had to revert the update as it was affecting a production site but I still have the logs if that helps.

I tried to replicate using MAMP locally but it worked fine. I'm guessing maybe it has something to do with permissions? Does Github Updater trying to use composer after install or something?

**Comment by afragen** [comment]
Composer is used by me and the `vendor` directory is in the download. 

Very curious. If you want to email me the logs or post them somewhere I’d be curious to see if I can identify something.

**Comment by vilmosioo** [comment]
Honestly, it's not much more than the original error

```
[Wed Feb 20 21:25:25.087572 2019] [proxy_fcgi:error] [pid 10917:tid 140566125786880] [client 172.31.29.145:61398] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Fragen\\Singleton' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/GHU_Trait.php:50
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Init.php(33): Fragen\\GitHub_Updater\\Init->load_options()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(57): Fragen\\GitHub_Updater\\Init->__construct()
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(20): Fragen\\GitHub_Updater\\Bootstrap->run('/opt/bitnami/ap...', '/opt/bitnami/ap...')
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/github-updater.php(53): require_once('/opt/bitnami/ap...')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(305): include_once('/opt/bitnami/ap...')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(108): require_once('/opt/bitnami/ap...')
...
', 
[Wed Feb 20 21:25:28.200819 2019] [proxy_fcgi:error] [pid 12467:tid 140566050252544] [client 172.31.60.139:54988] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Fragen\\Singleton' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/GHU_Trait.php:50
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Init.php(33): Fragen\\GitHub_Updater\\Init->load_options()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(57): Fragen\\GitHub_Updater\\Init->__construct()
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(20): Fragen\\GitHub_Updater\\Bootstrap->run('/opt/bitnami/ap...', '/opt/bitnami/ap...')
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/github-updater.php(53): require_once('/opt/bitnami/ap...')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(305): include_once('/opt/bitnami/ap...')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(108): require_once('/opt/bitnami/ap...')
...
'
[Wed Feb 20 21:25:31.122090 2019] [proxy_fcgi:error] [pid 11069:tid 140566234892032] [client 172.31.29.145:61406] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Fragen\\Singleton' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/GHU_Trait.php:50
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Init.php(33): Fragen\\GitHub_Updater\\Init->load_options()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(57): Fragen\\GitHub_Updater\\Init->__construct()
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(20): Fragen\\GitHub_Updater\\Bootstrap->run('/opt/bitnami/ap...', '/opt/bitnami/ap...')
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/github-updater.php(53): require_once('/opt/bitnami/ap...')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(305): include_once('/opt/bitnami/ap...')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(108): require_once('/opt/bitnami/ap...')
...
', 
[Wed Feb 20 21:25:33.400389 2019] [proxy_fcgi:error] [pid 11069:tid 140566100608768] [client 172.31.29.145:61410] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Fragen\\Singleton' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/GHU_Trait.php:50
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Init.php(33): Fragen\\GitHub_Updater\\Init->load_options()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(57): Fragen\\GitHub_Updater\\Init->__construct()
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(20): Fragen\\GitHub_Updater\\Bootstrap->run('/opt/bitnami/ap...', '/opt/bitnami/ap...')
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/github-updater.php(53): require_once('/opt/bitnami/ap...')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(305): include_once('/opt/bitnami/ap...')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(108): require_once('/opt/bitnami/ap...')
...
', 
[Wed Feb 20 21:25:37.600452 2019] [proxy_fcgi:error] [pid 12467:tid 140566083823360] [client 172.31.29.145:61418] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Fragen\\Singleton' not found in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Traits/GHU_Trait.php:50
Stack trace:
#0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Init.php(33): Fragen\\GitHub_Updater\\Init->load_options()
#1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(57): Fragen\\GitHub_Updater\\Init->__construct()
#2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/src/GitHub_Updater/Bootstrap.php(20): Fragen\\GitHub_Updater\\Bootstrap->run('/opt/bitnami/ap...', '/opt/bitnami/ap...')
#3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/github-updater/github-updater.php(53): require_once('/opt/bitnami/ap...')
#4 /opt/bitnami/apps/wordpress/htdocs/wp-settings.php(305): include_once('/opt/bitnami/ap...')
#5 /opt/bitnami/apps/wordpress/htdocs/wp-config.php(108): require_once('/opt/bitnami/ap...')
...
'
```

**Comment by afragen** [comment]
Can you make sure this file is set up correctly for you?

It’s part of the composer autoloader. Also make sure `vendor/afragen/singleton/Singleton.php` exists too. 

https://github.com/afragen/github-updater/blob/develop/vendor/composer/autoload_classmap.php

**Comment by afragen** [comment]
Closing for lack of response.
